name: CI Autotests Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  run-autotests:
    name: Run Tests and Deploy Report
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получение кода
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Даем права на выполнение gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Шаг 3: Установка Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Шаг 4: Запуск тестов
      - name: Run tests
        run: ./gradlew clean test

      # Шаг 5: Установка Allure через Action
      - name: Install Allure
        uses: simple-elf/allure-report-action@v1.7

      # Шаг 6: Генерация отчета
      - name: Generate Allure Report
        run: |
          /home/runner/allure/bin/allure generate build/allure-results -o allure-report --clean

      # Шаг 7: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report