name: CI Autotests Run

#Триггеры для запуска
on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Добавляем ручной запуск

#Разрешения для работы
permissions:
  id-token: write
  pages: write

#Задания
jobs:
  run-autotests:
    name: Run Tests and Deploy Report
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получение кода
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установка Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Шаг 3: Запуск тестов
      - name: Run tests
        run: ./gradlew clean test

      # Шаг 4: Установка Allure
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      # Шаг 5: Генерация Allure отчета
      - name: Generate Allure Report
        run: allure generate build/allure-results -o allure-report --clean

      # Шаг 6: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
